# Estructura del sitio TopeRC.es utilizando Jekyll

tiktok_username: "toperc.es"
instagram_username: "toperc.es"
youtube_username: "@TopeRC-es"


# Archivo de configuración principal de Jekyll
baseurl: "" # La URL base de tu sitio web
url: "http://toperc.es" # La URL completa de tu sitio web
title: "TopeRC"
description: >-
  El sitio número uno para amantes de coches radiocontrol.
  Reviews, guías, modificaciones y recambios para coches 
  RC de diferentes escalas y marcas.
author: "TopeRC Team"
markdown: kramdown
permalink: /:categories/:title/

theme: minima # Tema base para facilitar el diseño
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

disqus: toperc # Para comentarios en las reviews

collections:
  recambios:
    output: true
    permalink: /recambios/:path/