# Social usernames
tiktok_username: "toperc.es"
instagram_username: "toperc.es"
youtube_username: "@TopeRC-es"

# Base Config
baseurl: "" # La URL base de tu sitio web
url: "http://toperc.es" # La URL completa de tu sitio web
title: "TopeRC"
author: "TopeRC Team"
description: >-
  El sitio número uno para amantes de coches radiocontrol.
  Reviews, guías, modificaciones y recambios para coches 
  RC de diferentes escalas y marcas.
markdown: kramdown
permalink: /:categories/:title/
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-toc

# Third-party applications
disqus: toperc

# Paginación del blog
paginate: 5
paginate_path: "/blog/page:num"


# Collections
collections:
  tag:
    permalink: /tag/:title
    output: true

show_excerpts: true

defaults:
  - scope:
      path: ""
      type: "tag"
    values:
      layout: tag_page
  - scope:
      path: ""
    values:
      toc: true
      excerpt_separator: <!--more-->